runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
  
handlers:
- url: /los/
  static_files: /los/index.html
  upload: /los/index.html
